name : perl-blead

on: 
  push: *
  schedule:
    - cron: '*/20 * * * *'

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t tibtibdocker/perl-blead .
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        run: docker push tibtibdocker/perl-blead
