name: perl-blead-from-action

on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - name: Fetch repository
        uses: actions/checkout@master

      - name: Publish docker
        id: docker
        uses: zenato/docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tibtibdocker/perl-blead
          tag: latest
